### ISSUE TITLE
[Question] Is your old blacklist still available?

### ISSUE THREAD

**Issue by T145** [michael-ecklund/next-netlify-starter-netlify#1]
I ran across this URL: http://www.michaelbrentecklund.com/whm-cpanel-cphulk-banlist-whm-cpanel-cphulk-blacklist/
And through some simple tracking traced it back to here.
Just out of curiosity, is this list or service still available somewhere?

**Comment by michael-ecklund** [comment]
no, not available anymore. sorry.
